version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8087:80"  # Map host port 8080 to container port 80
    volumes:
      - .:/usr/share/nginx/html/ # Mount the local 'index.html' to replace the default one
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
