version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./static:/usr/share/nginx/html
    networks:
      - azizi-bridge

networks:
  azizi-bridge:
    driver: bridge
